Dockerfile
Makefile
confs/install.sh

Add makefile to launch & manage exegol
Add tmux & arsenal

makefile + arsenal + tmux

---

README.md
exegol.py
sources/zsh/zshrc

oh-my-zsh update seems to have removed the "prompt_char" command

Fixed post oh-my-zsh update issue

---

.gitignore
sources/install.sh

Fix to README and to feroxbuster's install
Added a cme module (Machine Account Quota)

Minor fixes

---

sources/install.sh

Fix jtr install

---

sources/install.sh
sources/zsh/history

https://github.com/sec-it/pass-station

Added PassStation (Default credentials database)

---

sources/install.sh
sources/zsh/history

https://github.com/HashPals/Name-That-Hash

Added Name-That-Hash

---

sources/install.sh
sources/zsh/history

Added sshpass and a default VIM configuration (https://github.com/amix/vimrc) for making it usable out of the box.

Added sshpass and a default VIM configuration

---

sources/install.sh
sources/zsh/history

Hey I added some new tools : 
- [Nuclei](https://github.com/projectdiscovery/nuclei)
- [Prips](http://www.ubuntugeek.com/prips-print-ip-address-on-a-given-range.html)
- [Hakrevdns](https://github.com/hakluke/hakrevdns)
I also add some example commands for these new tools & some useful commands history for pentest  engagement.
I have been working with exegol the past few days and it's really awesome ! Thx for the good work  :fire:

Added new tools: prips, hakrevdns, nuclei & some commands in history

---

sources/install.sh

Hola ! Je propose quelques tools incontournables pour la version light (j'ai pas tout le temps la fibre faut pas être trop gourmand non plus)

Add few tools for light version

---

sources/install.sh

Replace old gobuster with version 3

---

sources/install.sh
sources/zsh/history

Hello 
I used to work with robotstester from @p0dalirius on pentesting engagement & I found this tools really useful.
So I just add it to Exegol.
Repo of robotstester: https://github.com/p0dalirius/robotstester

Added new tool: robotstester.py

---

README.md
TODO.md
exegol/console/ConsoleFormat.py
exegol/console/TUI.py
exegol/console/cli/actions/Command.py
exegol/console/cli/actions/ExegolParameters.py
exegol/manager/ExegolManager.py
exegol/model/ContainerConfig.py
exegol/utils/ConstantConfig.py
exegol/utils/DockerUtils.py
tests/test_exegol.py

- Add --skip-images option on update
- Support GUI java apps on wayland env
- And minor updates
- #84 
- #86

Exegol 4.0.1

---

README.md
exegol/console/TUI.py
exegol/console/cli/actions/GenericParameters.py
exegol/manager/ExegolManager.py
exegol/model/ContainerConfig.py
exegol/utils/ConstantConfig.py
exegol/utils/UserConfig.py
exegol/utils/WebUtils.py
tests/test_exegol.py

Minor release, bug fix only.
- Blocking error when using Exegol offline without the `--offline` option
- Fix old parameter name in interactive command builder

Exegol 4.1.1

---

exegol/console/TUI.py
exegol/console/cli/actions/GenericParameters.py
exegol/manager/ExegolManager.py
exegol/model/ContainerConfig.py

Adding ability to comment containers

---

.github/workflows/entrypoint_release.yml
exegol/config/ConstantConfig.py
exegol/model/ContainerConfig.py
exegol/model/ExegolImage.py
exegol/utils/DataFileUtils.py
exegol/utils/DockerUtils.py
tests/test_exegol.py

Minor update with bug fixes.
- #156 
- HTTP Error after docker image installation

Exegol 4.2.1

---

exegol/model/ExegolImage.py

Type check catchup
- Type check syntax

Type check catch up

---

exegol/config/ConstantConfig.py
exegol/console/ExegolPrompt.py
exegol/manager/UpdateManager.py
tests/test_exegol.py

Minor bug fix
- Some rich bracket didn't show

Release 4.3.1

---

exegol/utils/WebUtils.py

I added proxy support to the wrapper :)
The wrapper was not using my system proxy, unable to retrieve exegol images/resources.
To avoid timeouts due to proxy processing, I doubled the request timeout time (from 5,10 to 10, 20).

Add proxy support

---

.github/workflows/entrypoint_release.yml

Fix TestPypi update blocking release pipeline

Remove TestPypi for pipeline release

---

tests/test_exegol.py

Fix test version for new release

Fix test version

---

setup.py

Update `setup.py` adding dynamic requirements

Update setup.py adding dynamic requirements

---

exegol/config/EnvInfo.py
exegol/utils/GuiUtils.py

Just a small typo I stumbled across while reading the source code 😄

fix: s/WLS2/WSL2

---

exegol/manager/ExegolManager.py
exegol/model/ExegolContainer.py

- Fix f-string syntax for python 3.11 and before

Fix f-string typo for python 3.11
