exegol.py

I used black (https://github.com/psf/black) to reformat the code & make it easier to read.
Also changed `command.replace("  ", " ").split(" ")` to `command.split()` that will split every consecutive blankspace as one & changed the `split("\n")` to `splitlines()

Refomarting exegol.py & modify splits methods

---

sources/install.sh
sources/zsh/history

Hey @ShutdownRepo!
In this PR I'd like bring [DivideAndScan](https://github.com/snovvcrash/DivideAndScan) tool to Exegol.
It is used to efficiently automate port scanning routine by splitting it into 3 phases:
1. Discover open ports for a bunch of targets.
2. Run Nmap individually for each target with version grabbing and NSE actions.
3. Merge the results into a single Nmap report (different formats available).
For the 1st phase a *fast* port scanner is intended to be used ([Masscan](https://github.com/robertdavidgraham/masscan) / [RustScan](https://github.com/RustScan/RustScan)), whose output is parsed and stored in a database ([TinyDB](https://github.com/msiemens/tinydb)). Next, during the 2nd phase individual Nmap scans are launched for each target with its set of open ports …

Added DivideAndScan tool

---

exegol.py

Added support for syncing timezones
The following options are enabled by default. They can all be disabled with the advanced option "`--no-default`". They can then be enabled back separately, for example "`exegol --no-default --X11 start`"
- `-x`, `--X11`             enable display sharing to run GUI-based applications
- **`--host-timezones`      let the container share the host's timezones configuration**
- `--host-network`        let the container share the host's networking namespace (the container shares the same interfaces and has the same adresses, needed for mitm6)
- `--bind-resources`      mount the `/opt/resources` of the container in a subdirectory of host's `/tmp/aa/Exegol/shared-resources`
- `-s {zsh,tmux,bash}`, `--shell {zsh,tmux,bash}`
select shell to start when entering …

Added support for syncing timezones

---

sources/install.sh

Hey!
A small pull request to install missing optional dependencies for autorecon, and making the python script executable by default as it was not.
Please let me know if you needed an issue for this, I will create it :slightly_smiling_face: .
Trace:
```
[Dec 23, 2021 - 12:42:06 (UTC)] exegol-stable /data # autorecon 192.168.176.247
zsh: permission denied: /opt/tools/AutoRecon/autorecon.py
[Dec 23, 2021 - 12:49:25 (UTC)] exegol-stable /data # chmod +x /opt/tools/AutoRecon/autorecon.py
[Dec 23, 2021 - 12:49:27 (UTC)] exegol-stable /data # autorecon 192.168.176.247
[!] The wkhtmltoimage program could not be found. Make sure it is installed. (On Kali, run: sudo apt install wkhtmltopdf)
[!] The oscanner program could not be found. Make sure it is installed. (On Kali, run: sudo apt install …
```

Fixed autorecon install

---

exegol/model/ContainerConfig.py

When using wayland compositor (in my case *sway*) some graphic applications (*ghidra* and *jd-gui* at least) have blank windows or weird size (for *burp*). Setting **_JAVA_AWT_WM_NONREPARENTING** to **1** seems to fix the problem. 
Source: https://discourse.ubuntu.com/t/environment-variables-for-wayland-hackers/12750

Fix GUI application for wayland compositor

---

README.md
TODO.md
exegol/console/TUI.py
exegol/console/cli/actions/GenericParameters.py
exegol/manager/ExegolManager.py
exegol/model/ContainerConfig.py
exegol/model/ExegolContainer.py
exegol/utils/ConstantConfig.py
exegol/utils/EnvInfo.py
exegol/utils/ExeLog.py
exegol/utils/GitUtils.py
exegol/utils/GuiUtils.py
tests/test_exegol.py

- **GUI** support on **MacOS** with XQuartz integration
- It is now possible to share ports (Docker NAT) between the host and the container (when the sharing of the host's network is not enabled or possible) with `-p` or `--port`
- Improve environment detection (Mac / Docker desktop) 
- #86 
- Update docker desktop unsupported features
- Some minor bug fix

Exegol 4.0.2

---

README.md

The README states the following in the pre-requisites: 
`Tips for running docker without sudo: sudo usermod -aG docker $(id -u -n)`
This commands adds the current user to the docker group ; granting privileges equivalent to root.
I believe that we should send the user to the docker documentation so that they can understand (be afraid of the big red box!) the security concerns emerging from managing docker as a non-root user.
They can also look at the alternatives (docker in rootless mode).

Remove dangerous command from readme

---

exegol/utils/GuiUtils.py

Tiny PR to send a warning message if DISPLAY environment variable is not set on host, which can prevents GUI commands to start
Fixes #148

Add warning message for unset DISPLAY env

---

exegol/model/ContainerConfig.py

Before the change, at the question "Do you want to disable ..." we had to enter y to enable

Fix inconsistency to enable shell logging

---

exegol/config/ConstantConfig.py
exegol/model/ExegolImage.py
requirements.txt
setup.py
tests/test_exegol.py

New minor version with some minor bug fix
- Fix typo in interactive configuration with #155 
- Constraint requests to 2.28.x as a temporary patch while the 2.29.x have some incompatibility

Exegol 4.2.2

---

exegol/config/ConstantConfig.py
exegol/config/EnvInfo.py
exegol/manager/ExegolManager.py
exegol/manager/UpdateManager.py
exegol/utils/GuiUtils.py
requirements.txt
setup.py
tests/test_exegol.py

New minor version with some minor bug fix.
Adding support for Python 3.11 (through requirements upgrade). 
> For source installation remember to run `pip3 install --upgrade -r requirements.txt`
- Fix GUI test for WSL2 engine
- Fix docker & requests > 2.29.x
- Add Python 3.11 support
- Minor update for the upgrade message

 Exegol 4.2.3

---

exegol/utils/GitUtils.py

Just a minor wording improvement in the Git utils. Feel free to reject if it's not important to you.

fix typo and improve wording in Git success message

---

exegol/config/ConstantConfig.py
exegol/config/EnvInfo.py
exegol/manager/UpdateManager.py
exegol/model/ExegolContainer.py
exegol/utils/DockerUtils.py
exegol/utils/GitUtils.py
requirements.txt
setup.py
tests/test_exegol.py

Minor update with many fix
- Fix NoneType issue during image recovery #164 #168
- Upgrade requirements (fix requests python 3.11 issues)
- Fix typo #169
- Fix update error when offline
- Fix OrbStack support

Exegol 4.2.4

---

README.md
exegol/config/ConstantConfig.py
exegol/config/DataCache.py
exegol/console/TUI.py
exegol/manager/UpdateManager.py
exegol/model/ContainerConfig.py
exegol/model/ExegolContainer.py
exegol/model/ExegolContainerTemplate.py
exegol/model/ExegolImage.py
exegol/utils/DataFileUtils.py
exegol/utils/DockerUtils.py
exegol/utils/GuiUtils.py
exegol/utils/WebUtils.py
tests/test_exegol.py

Minor update with bug fix + Add BlackHat USA 2023 badge
- #171
- #167 
- Fix WebUtils UTF-8 encoding

Exegol 4.2.5

---

exegol/model/ContainerConfig.py

Catching exception when interface missing for Desktop beta feature

---

exegol/console/TUI.py
exegol/model/ExegolImage.py
exegol/utils/DockerUtils.py

Previously, the wrapper would show remote image compressed size when they were not installed.
This is because the real, uncompressed, size cannot be fetched through Dockerhub and because the compression factor is not publick knowledge.
I downloaded a few images and did the math
| Image  | Version | Arch | compressed (GB) | uncompressed (GB) | comp. rate | 
| ------- | ------- | ----- | ----------------- | --------------------- | ---------- |
| nightly | 15b188c0 | arm64 | 14.3 | 34.7 | 2.42 |
| web | 3.1.1 | arm64 | 6.5 | 15.1 | 2.32 |
| osint | 3.1.1 | arm64 | 3.2 | 8.2 | 2.56 |
| light | 3.1.1 | arm64 | 4.6 | 11.9 | 2.58 |
| full | 3.1.1 | arm64 | 13.9 | 33.9 |2.43  |
The comp. factor goes up to **x2.6**.
Taking this into account, I modified the wrapper to show that estimated size …

Show estimated images uncompressed size

---

exegol/console/cli/ExegolCompleter.py
exegol/console/cli/actions/ExegolParameters.py
exegol/manager/UpdateManager.py
exegol/utils/DockerUtils.py

Adding the `--build-path` that a user can set for the `exegol install` command for local builds to point to custom dockerfiles. This will be especially useful for external contributors that want to build a local image before creating a pull request on the images repo, without having to mess around with their official exegol install.
Before this option, contributors would have to do something like 
```bash
mv "/path/to/Exegol/exegol-docker-build" "/path/to/Exegol/exegol-docker-build.bak"
cp -r "/path/to/custom_exegol-docker-build" "/path/to/Exegol/exegol-docker-build"
exegol install "myimage" "myprofile"
```
This would also allow contributors to have their own forks as well as their official exegol install without changes that they would be able to keep up to date (which wouldn't be …

Custom dockerfiles path for local builds

---

exegol/config/EnvInfo.py
exegol/model/ContainerConfig.py
exegol/utils/GuiUtils.py

Hey @Dramelac,
Here's an addition to set the correct environment variables for **wayland**. I started with this observation:
```bash
docker run -it -e XDG_RUNTIME_DIR=/tmp -e WAYLAND_DISPLAY=$WAYLAND_DISPLAY -v $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY debian bash
```
```bash
➜  ~ echo $WAYLAND_DISPLAY
wayland-1
```
```bash
[*] Location of the exegol workspace on the host : /home/qu35t/.exegol/workspaces/htb
[+] Opening shell in Exegol 'htb'
[-] The xhost command is not available on your host. Exegol was unable to allow your container to access your graphical environment (or you don't have one).
[Jan 26, 2024 - 21:53:47 (CET)] exegol-htb /workspace # firefox
Authorization required, but no authorization protocol specified
Error: cannot open display: :0
```
I've modified the …

Wayland support

---

exegol/console/cli/SyntaxFormat.py
exegol/console/cli/actions/GenericParameters.py
exegol/model/ContainerConfig.py

Code modified to expose port ranges rather than just ports.
In fact, in environments where it's not possible to have a bridged network, it's a pain to expose several ports at once.
The port exposure feature has been changed to allow commands of this kind: 
exegol start dev -p 9000-9010:9000-9010 -p 80 -p 802-805:udp
The feature has been extensively tested, but I have two points to make.
1. Creation timeout
First of all, if a port range is too large, it is possible to be timeout by exegol.
More precisely, if the machine takes longer than 60 seconds to create, exegol stops. I didn't touch this behavior to avoid blocking the user. In this case, the long creation time is not linked to exegol but to docker.
It's starting to be difficult to create a container with more than 2500 published …

FEATURE - Add range port

---

exegol/config/EnvInfo.py
exegol/console/TUI.py
exegol/model/ContainerConfig.py
exegol/model/ExegolContainer.py
exegol/utils/GuiUtils.py

> Internal pull request for quick review before beta-testing in dev branch
- Add support of wayland environment. Can work without X11 but some applications might support only X11.
- Handle docker error on container start (avoid stack-trace for end user and provide a better error message)
Note: hint when xhost command is missing is already added in the dev branch.
Thanks @QU35T-code for the help on the feature ;)

Add Feat/wayland to dev branch

---

.github/workflows/entrypoint_nightly.yml
.github/workflows/entrypoint_prerelease.yml
.github/workflows/entrypoint_pull_request.yml
.github/workflows/entrypoint_release.yml
.github/workflows/sub_testing.yml
README.md
exegol/config/ConstantConfig.py
exegol/config/EnvInfo.py
exegol/config/UserConfig.py
exegol/console/TUI.py
exegol/manager/ExegolManager.py
exegol/manager/UpdateManager.py
exegol/model/ContainerConfig.py
exegol/model/ExegolContainer.py
exegol/utils/DockerUtils.py
exegol/utils/GuiUtils.py
exegol/utils/WebUtils.py
tests/test_exegol.py

Wayland Update !
New minor wrapper version with various bug fix and improvements.
- Support for **Wayland** GUI (there is still some app that require a X11 socket)
- Better handling of docker errors
- Prevent timezone sharing on Mac (cause error on host package upgrade)
- Add proxy support (thanks to @Siopy)
- Handle docker timeout
- Add user hint when `xhost` isn't available
- #194

 Release 4.3.2

---

.github/workflows/entrypoint_nightly.yml
.github/workflows/entrypoint_release.yml
exegol/config/ConstantConfig.py
exegol/config/EnvInfo.py
exegol/console/cli/ExegolCompleter.py
exegol/manager/ExegolController.py
exegol/manager/ExegolManager.py
exegol/manager/UpdateManager.py
exegol/model/ContainerConfig.py
exegol/utils/DataFileUtils.py
exegol/utils/DockerUtils.py
exegol/utils/GitUtils.py
exegol/utils/GuiUtils.py
exegol/utils/MetaSingleton.py

New minor update with some bug fixing and improved error message.
- Fix auto-completion when using `sudo` (check the documentation to use `sudo exegol` correctly).
- Fix git branch name truncation
- Handle `None` config file
- Handle docker socket permission denied

Release 4.3.3

---

exegol/model/ContainerConfig.py

> Adding the filter to whitelist the device /dev/net/tun

Docker desktop add device whitelist

---

.gitattributes
.github/workflows/entrypoint_nightly.yml
exegol/config/ConstantConfig.py
requirements.txt
setup.py
tests/test_exegol.py

- New tests before release
- Update tzlocal requirement only for Mac and Windows environments
- Fix pip package requirements error
- Force windows env to clone bash script with LF linefeed

Release 4.3.6

---

exegol/model/ExegolContainer.py

This PR aims to bring support for X11 forwarding when the host is accessed by SSH from a remote location running a X server.
On top of xhost ACLs I created a secret sharing mechanism between the host and the Exegol container.
Some people on the discord server were asking about forwarding the GUI of Exegol containers to a remote location.
I tried this solution with only 2 setups: 
* Linux ==SSH==> Linux ==WRAPPER==> Exegol container
* Windows ==SSH==> Linux ==WRAPPER==> Exegol container
The following setups are yet to be tested:
* ? ==SSH==> Mac ==WRAPPER==> Exegol container
* ? ==SSH==> Windows ==WRAPPER==> Exegol container
I imported the subprocess library to get the output of a command. An alternative would be to create a file in the container workspace to pass the xauth cookie with …

Adding support for x11 forwarding

---

exegol/config/ConstantConfig.py
exegol/manager/ExegolManager.py
exegol/manager/UpdateManager.py
exegol/model/ExegolContainer.py
exegol/model/ExegolImage.py
exegol/utils/DockerUtils.py
exegol/utils/GitUtils.py
exegol/utils/WebUtils.py

New minor version including some bug fixes, improved waiting UI and the detection of `pipx` installation to show the correct upgrade command.
- Handle new Dockerhub API manifest v2 #238 
- Fix X11 forwarding container startup sequence #237 
- Fix wrapper latest version update

 Release 4.3.8

---

exegol/config/ConstantConfig.py
exegol/config/EnvInfo.py
exegol/manager/ExegolManager.py
exegol/utils/DataFileUtils.py
exegol/utils/GuiUtils.py

New minor version including some bug fixes and the `desktop` feature will automatically be enabled when a custom desktop config is supplied.
- #242

Release 4.3.9

---

exegol/config/ConstantConfig.py
exegol/config/DataCache.py
exegol/config/EnvInfo.py
exegol/console/cli/actions/Command.py
exegol/model/ContainerConfig.py
exegol/model/ExegolContainer.py
exegol/utils/DockerUtils.py
exegol/utils/GuiUtils.py
exegol/utils/imgsync/entrypoint.sh

- Improve my-resources loading time and logs
- Configure `$SHELL` variable for interactive sessions
- Disable Docker Desktop tips when using Exegol from Windows
- Fix X11 forwarding via SSH #237
- OpenVPN with multiple file can now use relative path

 Release 4.3.11
